---
title: "Comparison of ICE Aug 2026 versus Mar 2026 releases"
format:
  html:
    toc: true
    toc-depth: 3
    df-print: kable
execute:
  warning: false
  message: false
  echo: false
  freeze: true
---

```{r}
#| label: setup

library(dplyr)
library(arrow)
library(readxl)
library(tidyr)
library(tidylog)
library(purrr)
library(stringr)
library(lubridate)
library(knitr)
library(ggplot2)
library(pointblank)

data_dir <- here::here("inputs/")
mar_dir <- paste0(data_dir, "/2026-03-11/")
aug_dir <- paste0(data_dir, "/2026-08-07/")

```

# Detentions

```{r}
#| warning: false
#| message: false

# ---- Read in files ----
col_types_mar <- c(
  "date", # Stay Book In Date Time
  "date", # Book In Date Time
  "text", # Detention Facility
  "date", # Book Out Date Time
  "date", # Stay Book Out Date Time
  "text", # Detention Release Reason
  "date", # Stay Book Out Date
  "text", # Stay Release Reason
  "text", # Religion
  "text", # Gender
  "text", # Marital Status
  "text", # Ethnicity
  "text", # Birth Country
  "text", # Citizenship Country
  "text", # Entry Status
  "text", # Known Terrorist Yes No
  "text", # Suspected Gang Yes No
  "text", # MSC Charge
  "numeric", # MSC Sentence Days
  "numeric", # MSC Sentence Months
  "numeric", # MSC Sentence Years
  "text", # MSC Charge Code
  "text", # Aggravated Felon Yes No
  "text", # Offense INA 236C Yes No
  "text", # Case INA 236C Yes No
  "date", # Bond Posted Date
  "numeric", # Bond Posted Amount
  "text", # Case Status
  "text", # Case Category
  "text", # Final Order Yes No
  "date", # Final Order Date
  "text", # Case Threat Level
  "text", # Detainee Classification
  "text", # Final Charge
  "date", # Departed Date
  "text", # Departure Country
  "numeric", # Initial Bond Set Amount
  "date", # Initial Bond Set Date
  "text", # Detention Facility Code
  "text", # Birth Date
  "numeric", # Birth Year
  "text", # Book In Criminality
  "text", # Race
  "date", # Entry Date
  "text", # Apprehension Final Program
  "date", # MSC Charge Date
  "date", # MSC Conviction Date
  "text", # MSC Criminal Charge Status
  "text", # MSC Criminal Charge Status Code
  "text", # MSC Crime Class
  "text", # Book In Site
  "text", # Book In AOR
  "text" # Anonymized Identifier
)

col_types_aug <- c(
  "numeric", # Birth Year
  "numeric", # Bond Posted Amount
  "date", # Bond Posted Date
  "text", # Book In Criminality
  "date", # Detention Book In Date Time
  "text", # Case Category
  "text", # Case Status
  "text", # Case Threat Level
  "text", # Citizenship Country
  "date", # Departed Date
  "text", # Departure Country
  "date", # Detention Book Out Date Time
  "text", # Detention Facility
  "text", # Detention Facility Code
  "text", # Detention Release Reason
  "date", # Entry Date
  "text", # Entry Status
  "text", # Ethnicity
  "text", # Felon
  "text", # Final Charge
  "date", # Final Order Date
  "text", # Final Order Yes No
  "text", # Apprehension Final Program
  "text", # Gender
  "text", # Initial Bond Set Amount
  "text", # Marital Status
  "text", # MSC Charge
  "text", # Religion
  "date", # Stay Book In Date Time
  "date", # Stay Book Out Date Time
  "text", # Stay Release Reason
  "text", # Apprehension Final Program Group
  "text", # Alien File Number
  "text" # Anonymized Unique Identifier
)

# ---- Read in data ----

detentions_df_mar <-
  list.files(
    mar_dir,
    pattern = "^[^~].*Detentions",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_mar,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )

detentions_df_aug <-
  list.files(
    aug_dir,
    pattern = "^[^~].*DET",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_aug,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )

# ---- Check: read ----
detentions_df_mar |>
  col_exists(
    c(
      `Stay Book In Date Time`,
      `Book In Date Time`,
      `Detention Facility Code`,
      `Anonymized Identifier`,
      `Gender`,
      `Case Status`
    )
  ) |>
  col_vals_not_null(
    `Stay Book In Date Time`,
    actions = action_levels(warn_at = 0.01, stop_at = 0.05)
  ) |>
  invisible()

detentions_df_aug |>
  col_exists(
    c(
      `Stay Book In Date Time`,
      `Detention Book In Date Time`,
      `Detention Facility Code`,
      `Anonymized Unique Identifier`,
      `Gender`,
      `Case Status`
    )
  ) |>
  col_vals_not_null(
    `Stay Book In Date Time`,
    actions = action_levels(warn_at = 0.01, stop_at = 0.05)
  ) |>
  invisible()

```


## August 2026 data
```{r}

kable(head(detentions_df_aug))

```

## March 2026 data
```{r}

kable(head(detentions_df_mar))

```

## Naive cleaning
```{r}

detentions_df_mar <- detentions_df_mar |>
  janitor::clean_names()

detentions_df_aug <- detentions_df_aug |>
  janitor::clean_names()

```

# Book-ins per week

Plots match

```{r}

dat_mar <- detentions_df_mar |>
  mutate(week = floor_date(book_in_date_time, unit="weeks")) |>
  count(week) |>
  mutate(source = "2026-03 release")

dat_aug <- detentions_df_aug |>
  mutate(week = floor_date(detention_book_in_date_time, unit="weeks")) |>
  count(week) |>
  mutate(source = "2026-08 release")

dat <- rbind(dat_mar, dat_aug)

p1 <- dat |>
  ggplot(aes(x = week, y = n, color = source, group = source)) +
  geom_line()

p1

p2 <- dat |>
  filter(week >= "2022-10-01") |>
  ggplot(aes(x = week, y = n, color = source, group = source)) +
  geom_line()

p2


```

## New facilities
```{r}

mar_facils <- unique(detentions_df_mar$detention_facility_code)

aug_facils <- unique(detentions_df_aug$detention_facility_code)

new_facils <- setdiff(aug_facils, mar_facils)

```
