---
title: "Comparison of ICE Aug 2026 versus Mar 2026 releases"
format:
  html:
    toc: true
    toc-depth: 3
    df-print: kable
execute:
  warning: false
  message: false
  echo: false
  freeze: true
---

```{r}
#| label: setup

library(dplyr)
library(arrow)
library(readxl)
library(tidyr)
library(tidylog)
library(purrr)
library(stringr)
library(lubridate)
library(knitr)
library(ggplot2)
library(pointblank)

data_dir <- here::here("inputs/")
mar_dir <- paste0(data_dir, "/2026-03-11/")
aug_dir <- paste0(data_dir, "/2026-08-07/")

```

# Encounters

```{r}

# ---- Read in files ----

col_types_aug <- c(
"numeric", # Birth Year
"text", # Case Category
"text", # Case Status
"text", # Citizenship Country
"date", # Departed Date
"text", # Departure Country
"text", # Encounter Criminality
"date", # Event Date
"text", # Event Type
"date", # Final Order Date
"text", # Final Order Yes No
"text", # Final Program
"text", # Final Program Group
"text", # Gender
"text", # Event Landmark
"text", # Lead Event Type
"text", # Lead Source
"text", # Processing Disposition
"text", # Responsible AOR
"text", # Responsible Site
"text", # Alien File Number
"text" # Anonymized Unique Identifier
)

col_types_mar <- c(
"date", # Event Date
"text", # Event Type
"text", # Event Landmark
"text", # Operation
"text", # Encounter Threat Level
"text", # Responsible AOR
"text", # Responsible Site
"text", # Lead Event Type
"text", # Lead Source
"text", # Final Program
"text", # Arresting Agency
"text", # Encounter Criminality
"text", # Processing Disposition
"text", # Case Status
"text", # Case Category
"date", # Departed Date
"text", # Departure Country
"text", # Final Order Yes No
"text", # Final Order Date
"numeric", # Birth Year
"text", # Citizenship County
"text", # Gender
"text" # Anonymized Identifier
)


encounters_df_aug <-
  list.files(
    aug_dir,
    pattern = "^[^~].*ENC",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_aug,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )

encounters_df_mar <-
  list.files(
    mar_dir,
    pattern = "^[^~].*Encounters",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_mar,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )


# ---- Read in to temporary file ----
url <- "https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1951492254031"
f <- tempfile(fileext = ".xlsx")
download.file(url, f, mode = "wb")

col_types_jul25 <- c(
  "date", # Event Date
  "text", # Responsible AOR
  "text", # Responsible Site
  "text", # Lead Event Type
  "text", # Lead Source
  "text", # Event Type
  "text", # Final Program
  "text", # Final Program Group
  "text", # Encounter Criminality
  "text", # Processing Disposition
  "text", # Case Status
  "text", # Case Category
  "date", # Departed Date
  "text", # Departure Country
  "text", # Final Order Yes No
  "date", # Final Order Date
  "text", # Birth Date
  "numeric", # Birth Year
  "text", # Citizenship Country
  "text", # Gender
  "text", # Event Landmark
  "text", # Alien File Number
  "text", # EID Case ID
  "text", # EID Subject ID
  "text" # Unique Identifier
)

sheets <- readxl::excel_sheets(f) |> set_names()

encounters_df_jul25 <- map_dfr(
  sheets,
  ~ readxl::read_excel(
    path = f,
    sheet = .x,
    col_types = col_types_jul25,
    skip = 6
  ),
  .id = "sheet_original"
)


col_types_oct25 <- c(
  "date", # Event Date
"text", # Responsible AOR
"text", # Responsible Site
"text", # Lead Event Type
"text", # Lead Source
"text", # Event Type
"text", # Final Program
"text", # Final Program Group
"text", # Encounter Criminality
"text", # Processing Disposition
"text", # Case Status
"text", # Case Category
"date", # Departed Date
"text", # Departure Country
"text", # Final Order Yes No
"text", # Final Order Date
"text", # Birth Date
"numeric", # Birth Year
"text", # Citizenship Country
"text", # Gender
"text", # Event Landmark
"text", # Alien File Number
"text", # EID Case ID
"text", # EID Subject ID
"text" # Unique Identifier
)

url <- "https://ucla.box.com/shared/static/50e4ijapmw1ulnev07zf449q38xievjq.xlsx"
f <- tempfile(fileext = ".xlsx")
download.file(url, f, mode = "wb")

sheets <- readxl::excel_sheets(f) |> set_names()

encounters_df_oct25 <- map_dfr(
  sheets,
  ~ readxl::read_excel(
    path = f,
    sheet = .x,
    col_types = col_types_oct25,
    skip = 6
  ),
  .id = "sheet_original"
)

```


## Naive cleaning
```{r}

encounters_df_jul25 <- encounters_df_jul25 |> 
    janitor::clean_names() %>% 
  filter(event_date <= "2025-07-30")

encounters_df_oct25 <- encounters_df_oct25 |> 
    janitor::clean_names() %>% 
  filter(event_date <= "2025-10-31")

encounters_df_mar <- encounters_df_mar |> 
    janitor::clean_names()

encounters_df_aug <- encounters_df_aug |> 
    janitor::clean_names()

```


## Weekly counts

```{r}

dat_jul25 <- encounters_df_jul25 |> 
    mutate(week = floor_date(event_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2025-07 release")

dat_oct25 <- encounters_df_oct25 |> 
    mutate(week = floor_date(event_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2025-10 release")

dat_mar <- encounters_df_mar |> 
    mutate(week = floor_date(event_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2026-03 release")

dat_aug <- encounters_df_aug |> 
    mutate(week = floor_date(event_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2026-08 release")

dat <- rbind(dat_mar, dat_aug) |>
  rbind(dat_jul25) %>% 
  rbind(dat_oct25)

p1 <- dat |> 
    ggplot(aes(x = week, y = n, color = source, group = source)) +
    geom_line() + theme_minimal()

p1

```

