---
title: "Comparison of ICE Aug 2026 versus Mar 2026 releases"
format:
  html:
    toc: true
    toc-depth: 3
    df-print: kable
execute:
  warning: false
  message: false
  echo: false
  freeze: true
---

```{r}
#| label: setup

library(dplyr)
library(arrow)
library(readxl)
library(tidyr)
library(tidylog)
library(purrr)
library(stringr)
library(lubridate)
library(knitr)
library(ggplot2)
library(pointblank)

data_dir <- here::here("inputs/")
mar_dir <- paste0(data_dir, "/2026-03-11/")
aug_dir <- paste0(data_dir, "/2026-08-07/")

```

# Removals

```{r}

# ---- Read in to temporary file ----
url <- "https://ucla.box.com/shared/static/hrofkgyefmmvki95f487rpk1wigcefd5.xlsx"
f <- tempfile(fileext = ".xlsx")
download.file(url, f, mode = "wb")

col_types_jul25 <-
  c(
    "date", # Departed Date
    "text", # Port of Departure
    "text", # Departure Country
    "text", # Docket AOR
    "text", # Apprehension State
    "text", # Apprehension County
    "text", # Case Status
    "text", # Gender
    "text", # Birth Country
    "text", # Citizenship Country
    "text", # Birth Date
    "numeric", # Birth Year
    "date", # Entry Date
    "text", # Entry Status
    "text", # MSC NCIC Charge
    "text", # MSC NCIC Charge Code
    "date", # MSC Charge Date
    "text", # MSC Criminal Charge Status
    "text", # MSC Criminal Charge Status Code
    "date", # MSC Conviction Date
    "text", # Case Threat Level
    "text", # Case Criminality
    "text", # Felon
    "text", # Processing Disposition
    "text", # Case Category
    "text", # Final Program
    "text", # Final Program Code
    "text", # Case Category Time of Arrest
    "text", # Latest Arrest Program Current
    "text", # Latest Arrest Program Current Code
    "date", # Latest Person Apprehension Date
    "text", # Final Order Yes No
    "date", # Final Order Date
    "text", # Final Charge Code
    "text", # Final Charge Section Code
    "text", # Prior Deport Yes No
    "date", # Latest Person Departed Date
    "text", # Alien File Number
    "text", # EID Case ID
    "text", # EID Subject ID
    "text" # Unique Identifier
  )

col_types_aug26 <- c(
  "text", # Apprehension State
  "text", # Apprehension City
  "numeric", # Birth Year
  "text", # Case Category
  "text", # TOA Case Category
  "text", # Case Criminality
  "text", # Case Status
  "text", # Case Threat Level
  "text", # Citizenship Country
  "date", # Departed Date
  "text", # Departure Country
  "text", # Docket AOR
  "date", # Entry Date
  "text", # Entry Status
  "text", # Final Charge Code
  "text", # Final Charge Section
  "text", # Final Order Yes No
  "text", # Final Order Date
  "text", # Final Program
  "text", # Final Program Code
  "text", # Gender
  "date", # Apprehension Date
  "text", # Latest Apprehension Program Code
  "text", # Latest Apprehension Program
  "text", # MSC Charge
  "date", # MSC Charge Date
  "text", # MSC Charge Code
  "date", # MSC Conviction Date
  "text", # MSC Criminal Charge Status
  "text", # Port of Departure
  "text", # Prior Deport Yes No
  "text", # Progrocessing Disposition
  "text", # Arresting Agency
  "text", # Alien File Number
  "text" # Anonymized Unique Identifier
)

col_types_mar26 <- c(
  "date", # Departed Date
  "text", # Port of Departure
  "text", # Departure Country
  "text", # Case AOR
  "text", # State
  "text", # County
  "text", # Case Status
  "text", # Gender
  "text", # Birth Country
  "text", # Citizenship Country
  "text", # Birth Date
  "numeric", # Birth Year
  "date", # Entry Date
  "text", # Entry Status
  "text", # Known Terrorist Yes No
  "text", # Suspected Gang Yes No
  "text", # MSC Charge
  "date", # MSC Charge Date
  "text", # MSC Criminal Charge Status
  "text", # MSC Charge Code
  "text", # MSC Conviction Date
  "text", # Case Criminality
  "text", # Case Threat Level
  "text", # Aggravated Felon Yes No
  "text", # Processing Disposition
  "text", # Case Category
  "text", # Final Program
  "text", # Final Program Code
  "text", # Arresting Agency
  "text", # TOA Case Category
  "text", # Latest Apprehension Final Program
  "text", # Latest Arresting Agency
  "text", # Latest Apprehension Date
  "text", # Final Order Yes No
  "text", # Final Order Date
  "text", # Final Charge Code
  "text", # Final Charge Section
  "text", # Prior Deport Yes No
  "text" # Anonymized Identifier
)


removals_df_jul_25 <-
  readxl::read_excel(
    path = f,
    sheet = 1,
    col_types = col_types_jul25,
    skip = 6
  )





# ---- Read in files ----

removals_df_aug <-
  list.files(
    aug_dir,
    pattern = "^[^~].*REM",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_aug26,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )

removals_df_mar <-
  list.files(
    mar_dir,
    pattern = "^[^~].*Removals",
    full.names = TRUE
  ) |>
  set_names(basename) |>
  map_dfr(
    function(f) {
      readxl::excel_sheets(f) |>
        set_names() |>
        map_dfr(
          function(s) {
            readxl::read_excel(
              path = f,
              sheet = s,
              col_types = col_types_mar26,
              skip = 6
            )
          },
          .id = "sheet_original"
        )
    },
    .id = "file_original"
  )

```

## Naive cleaning
```{r}

removals_df_jul_25 <- removals_df_jul_25 |> 
    janitor::clean_names()

removals_df_mar <- removals_df_mar |> 
    janitor::clean_names()

removals_df_aug <- removals_df_aug |> 
    janitor::clean_names()

```


## Weekly counts

Removals align with March 2026 release, not preferred July 2025 release

```{r}

dat_jul_25 <- removals_df_jul_25 |> 
    mutate(week = floor_date(departed_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2025-07 release")

dat_mar <- removals_df_mar |> 
    mutate(week = floor_date(departed_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2026-03 release")

dat_aug <- removals_df_aug |> 
    mutate(week = floor_date(departed_date, unit="weeks")) |> 
    count(week) |> 
    mutate(source = "2026-08 release")

dat <- rbind(dat_mar, dat_aug) |>
  rbind(dat_jul_25)

p1 <- dat |> 
    ggplot(aes(x = week, y = n, color = source, group = source)) +
    geom_line() + theme_minimal()

p1

```

## Problem

Files FY2023 and FY2024 are identical, both cover FY 2023:

```{r}

date_range <- arrests_df_aug |> 
    group_by(file_original) |> 
    summarize(date_min = min(apprehension_date, na.rm=TRUE),
              date_max = max(apprehension_date, na.rm=TRUE))

print(date_range)

ars_2023 <- arrests_df_aug |> 
    filter(file_original == "Hausman_ARS_FY2023_LESA-STU_FINAL Highlighted.xlsx") |> 
    select(-file_original)

ars_2024 <- arrests_df_aug |> 
    filter(file_original == "Hausman_ARS_FY2024_LESA-STU_FINAL Highlighted.xlsx") |> 
    select(-file_original)

identical(ars_2023, ars_2024)

```
