name: Run Changed Scripts and Create Release

on:
  push:
    paths:
      - 'code/**'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner
    # container: ${{ contains(github.event.head_commit.modified, 'code/geography.R') && 'rocker/geospatial:4.5.1' || 'ubuntu:latest' }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::sf   # tells it which sysreqs to resolve
          needs: sysreqs            # only installs sysreqs, not R packages

      - uses: r-lib/actions/setup-renv@v2
      
      - run: mkdir -p outputs

      - uses: tj-actions/changed-files@v45
        id: cf
        with:
          files: |
            code/**/*.R          # only care about R files under code/

      - name: Run changed R scripts
        if: steps.cf.outputs.any_changed == 'true'
        run: |
          for f in ${{ steps.cf.outputs.all_changed_files }}; do
            echo "Running $f"
            Rscript --verbose "$f"
          done