name: Run Changed Scripts and Create Release

on:
  push:
    paths:
      - 'code/**'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner
    container: ${{ contains(github.event.head_commit.modified, 'code/geography.R') && 'rocker/geospatial:latest' || 'ubuntu:latest' }}

    steps:
      - uses: actions/checkout@v4
        with:      
          fetch-depth: 0 
          
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - run: mkdir -p outputs

      - id: changed-scripts
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^clean/' | grep '\.R$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - run: |
          echo "${{ steps.changed-scripts.outputs.files }}" | while read file; do
            echo "Running $file"
            Rscript --verbose "$file"
          done
        if: steps.changed-scripts.outputs.files != ''
