name: Run Changed Map Script and Create Release

on:
  push:
    paths:
      - 'maps/prep_map_data.R'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: ubuntu-latest
    container:
      image: rocker/geospatial:latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - run: | 
          mkdir -p outputs
          mkdir -p inputs

      - run: Rscript --verbose maps/prep_map_data.R

      - uses: ncipollo/release-action@v1
        if: steps.changed-scripts.outputs.files != ''
        with:
          tag: auto-${{ github.sha }}
          name: "Auto Release ${{ github.sha }}"
          artifacts: |
            outputs/*.feather
            outputs/*.zip
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
