name: Run Changed Scripts and Create Release

on:
  push:
    paths:
      - 'code/**'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          # Configure LFS to track files in data/ directory
          git lfs track "data/**"
          git add .gitattributes

      - uses: r-lib/actions/setup-r@v2

      - name: Install OS libs for sf
        if: contains(steps.cf.outputs.all_changed_files, 'code/geography.R')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev

      - uses: r-lib/actions/setup-renv@v2
      
      - run: | 
          mkdir -p tmp

      - uses: tj-actions/changed-files@v45
        id: cf
        with:
          files: |
            code/*.R
            code/**/*.R

      - name: Run changed R scripts
        if: steps.cf.outputs.any_changed == 'true'
        run: |
          for f in ${{ steps.cf.outputs.all_changed_files }}; do
            echo "Running $f"
            Rscript --verbose "$f"
          done

      - name: Check for new data files and commit to LFS
        run: |
          # Add any new files in data/ to git (will be tracked by LFS due to .gitattributes)
          if [ -n "$(git status --porcelain data/)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data/
            git add .gitattributes
            git commit -m "Add new data files via LFS [skip ci]" || echo "No changes to commit"
            git push
          fi