name: Run Changed Map Script and Create Release

on:
  push:
    paths:
      - 'clean/**'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: ubuntu-latest
    container:
      image: rocker/geospatial:latest

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            libudunits2
            libudunits2-dev
      
      - uses: actions/checkout@v4

      - run: git fetch --unshallow || true

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - run: mkdir -p outputs

      - run: mkdir -p inputs

      - id: changed-scripts
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^clean/prep_map' | grep '\.R$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - run: |
          echo "${{ steps.changed-scripts.outputs.files }}" | while read file; do
            echo "Running $file"
            Rscript "$file"
          done
        if: steps.changed-scripts.outputs.files != ''

      - uses: ncipollo/release-action@v1
        if: steps.changed-scripts.outputs.files != ''
        with:
          tag: auto-${{ github.sha }}
          name: "Auto Release ${{ github.sha }}"
          artifacts: |
            outputs/*.feather
            outputs/*.zip
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
