name: Run Changed Scripts and Create Release

on:
  push:
    paths:
      - 'code/**'

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner
    # container: ${{ contains(github.event.head_commit.modified, 'code/geography.R') && 'rocker/geospatial:4.5.1' || 'ubuntu:latest' }}
    container: 'rocker/geospatial:4.5.1'

    steps:
      - uses: actions/checkout@v4

      # - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - run: mkdir -p outputs

      - id: changed-scripts
        shell: bash
        run: |
          set -euo pipefail
          # Ensure we have the remote branch ref
          git fetch --no-tags --prune origin "+refs/heads/${GITHUB_REF_NAME}:refs/remotes/origin/${GITHUB_REF_NAME}"
          # Base = common ancestor of current HEAD and remote branch
          BASE=$(git merge-base HEAD origin/${GITHUB_REF_NAME})
          FILES=$(git diff --name-only "$BASE" HEAD | grep '^code/.*\.R$' || true)
          {
            echo "files<<'EOF'"
            echo "$FILES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Run changed R scripts
        if: steps.changed-scripts.outputs.files != ''
        shell: bash
        run: |
          set -euo pipefail
          echo "${{ steps.changed-scripts.outputs.files }}" | while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            echo "Running $f"
            Rscript --verbose "$f"
          done