name: Run Changed Scripts and Create Release

on:
  push:
    paths:
      - 'clean/**'

jobs:
  run-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Create outputs directory
        run: mkdir -p outputs

      - name: Fetch full git history for diff
        run: git fetch --unshallow || true

      - name: Get changed R scripts
        id: changed
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^clean/' | grep '\.R$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run changed R scripts
        if: steps.changed.outputs.files != ''
        run: |
          echo "${{ steps.changed.outputs.files }}" | while read file; do
            echo "Running $file"
            Rscript "$file"
          done

      - name: Create release and upload data files
        if: steps.changed.outputs.files != ''
        uses: ncipollo/release-action@v1
        with:
          tag: auto-${{ github.sha }}
          name: "Auto Release ${{ github.sha }}"
          artifacts: |
            outputs/*.xlsx
            outputs/*.feather
            outputs/*.sav
            outputs/*.dta
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}